name: Admin Sample CD

# Project templates come equipped with CI/CD for both Azure DevOps and GitHub, providing you with a hassle-free way to get started with your new project. It is important to note that you should not depend on the contents of this file. More info at https://bitplatform.dev/templates/dev-ops

env:
  API_SERVER_ADDRESS: 'https://adminpanel.bitplatform.dev/'
  APP_SERVICE_NAME: 'bit-adminpanel'

on:
  workflow_dispatch:
  push:
    branches: [ "macos-intel-test" ]

permissions:
  contents: read

jobs:

  build_blazor_hybrid_maccatalyst:
     name: build blazor hybrid (maccatalyst)
     runs-on: macos-13
   
     steps:
      
     - name: Checkout source code
       uses: actions/checkout@v3
      
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         global-json-file: src/Templates/Boilerplate/Bit.Boilerplate/global.json

     - uses: actions/setup-node@v3
       with:
        node-version: 18

     - name: Create project from Boilerplate
       run: |
        cd src/Templates/Boilerplate && dotnet build -c Release
        dotnet pack -c Release -o . -p:ReleaseVersion=0.0.0 -p:PackageVersion=0.0.0
        dotnet new install Bit.Boilerplate.0.0.0.nupkg
        cd ../../../ && dotnet new bit-bp --name AdminPanel --database SqlServer --sample Admin --offlineDb true
   
     - name: Update appsettings.json api server address
       uses: devops-actions/variable-substitution@v1.2 
       with:
         files: 'AdminPanel/src/Client/AdminPanel.Client.Core/appsettings.json'
       env:
         ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}
         ApplicationInsights.ConnectionString: ""

     - name: Install maui
       run: cd src && dotnet workload install maui
   
     - name: Generate CSS/JS files
       run: |
         dotnet build AdminPanel/src/Client/AdminPanel.Client.Core/AdminPanel.Client.Core.csproj -t:BeforeBuildTasks -p:Version="1" --no-restore
         dotnet build AdminPanel/src/Client/AdminPanel.Client.Maui/AdminPanel.Client.Maui.csproj -t:BeforeBuildTasks -p:Version="1" --no-restore
  
     - name: Build pkg
       run: dotnet build AdminPanel/src/Client/AdminPanel.Client.Maui/AdminPanel.Client.Maui.csproj -c Release -p:CreatePackage=true -p:ApplicationDisplayVersion="1" -p:ApplicationVersion="1.0.0" -p:ApplicationTitle="AdminPanel" -p:ApplicationId="com.bitplatform.AdminPanel.Template" -f net8.0-maccatalyst
   
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: mac-pkg-bundle
         path: AdminPanel/src/Client/AdminPanel.Client.Maui/bin/release/net8.0-maccatalyst/*.pkg
